### Чат с агентом

POST http://localhost:8000/api/agent
Accept: application/json
Content-Type: application/json

{
    "UserQuery": "Сгенерируй дружелюбное письмо и отформатируй в Markdown, добавь отступы где надо, так что бы текст был не широким и по центру и отправь письмо на почту some_email.com. Представься моим именем - Максим. Спроси как дела, здоровье, скажи что наша дружба очень важна. Собеседника зовут Данила."
}